version: '3'

services:

  app:

    build:
      context: .
      args:
        BUILDKIT_INLINE_DOCKERFILE: 1
    ports:

      - "8080:8080"

    depends_on:

      - db

    environment:

      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres

      - SPRING_DATASOURCE_USERNAME=user

      - SPRING_DATASOURCE_PASSWORD=1234

  db:

    image: postgres

    environment:

      - POSTGRES_DB=postgres

      - POSTGRES_USER=user

      - POSTGRES_PASSWORD=1234